#! /bin/sh

cp /etc/portage/patches/x11-libs/gtk+/gtkdbusgenerated.c .
cp /etc/portage/patches/x11-libs/gtk+/gtkdbusgenerated.h .
cp /etc/portage/patches/x11-libs/gtk+/gtkdbusgenerated.c ./gtk
cp /etc/portage/patches/x11-libs/gtk+/gtkdbusgenerated.h ./gtk
